### ISSUE TITLE
Crash when using version 1.1.3 due to MMDlib being a 1.11.2 mod

### ISSUE THREAD

**Issue by DeltaWolf7** [YaibaToKen/Armory-Expansion#22]
Minecraft: 1.12.2
Forge: 14.23.5.2824
Armory Expansion: 1.1.3
MMDLib: 1.0.0.2

`[20:59:20] [Server thread/FATAL] [FML]: The mod mmdlib does not wish to run in Minecraft version Minecraft 1.12.2. You will have to remove it to play.
[20:59:20] [Server thread/FATAL] [FML]: Wrong Minecraft version for mmdlib
[20:59:20] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for mmdlib
Wrong Minecraft Versions!
Mod: mmdlib
Location: .\mods\MMDLib-1.11.2-1.0.0.2.jar
Expected: [1.11.2,1.11.2]
Current: Minecraft 1.12.2
at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:250) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[20:59:20] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Minecraft1.12.2\.\crash-reports\crash-2019-03-30_20.59.20-server.txt`

Removing lib causes a missing mod error.

**Comment by YaibaToKen** [comment]
Version 1.1.3b was uploaded just now to fix that as I did not notice MMDLib has no public release for 1.12.2
